[package]
name = "dat0-engine"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
rust-version.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
duckdb.workspace = true
futures.workspace = true
tokio.workspace = true
tracing.workspace = true
thiserror.workspace = true
serde.workspace = true
async-trait.workspace = true
num_cpus.workspace = true
tempfile.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "fs", "sync", "time"] }
criterion = { workspace = true }
dat0-fixtures = { path = "../dat0-fixtures" }
tempfile = { workspace = true }

[[bench]]
name = "view_regen"
harness = false
